spring.application.name=genealogie
spring.datasource.url=${DB_URL}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none

client.secret.jwt=${CLIENT_JWT_SECRET}
jwt.token.validity=${JWT_TOKEN_VALIDITY}

